# Generated by Django 5.2 on 2025-04-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_plate',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
