# Generated by Django 5.2 on 2025-04-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_vehicle_vehicle_plate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
